/* export const songs = [
    {
      id:1,
      backgroundImage: "/assets/images/local-poster-1.jpg",
      posterUrl: "/assets/images/local-poster-1.png",
      title: "Calm Down",
      album: "Audio",
      year: 2023,
      artist: "Rema ft Gomez",
      musicPath: "/assets/music/local-music-2.mp3",
    },
    {
      id:2,
      backgroundImage: "/assets/images/local-poster-2.jpg",
      posterUrl: "/assets/images/local-poster-2.jpg",
      title: "Lonely at the top ",
      album: "Audio",
      year: 2023,
      artist: "Asake",
      musicPath: "/assets/music/local-music-1.mp3",
    },
    {
      id:3,
      backgroundImage: "/assets/images/local-poster-3.jpg",
      posterUrl: "/assets/images/local-poster-3.jpg",
      title: "Unavailable",
      album: "Audio",
      year: 2023,
      artist: "Davido ft Musa",
      musicPath: "/assets/music/local-music-3.mp3",
    },
    {
      id:4,
      backgroundImage: "/assets/images/poster-1.jpg",
      posterUrl: "/assets/images/poster-1.jpg",
      title: "Wotakoi: Love is Hard for an Otaku",
      album: "Anime",
      year: 2018,
      artist: "Sumika",
      musicPath: "/assets/music/music-1.mp3",
    },
    {
      id:5,
      backgroundImage: "/assets/images/poster-2.jpg",
      posterUrl: "/assets/images/poster-2.jpg",
      title: "AOT: My War",
      album: "Anime",
      year: 2020,
      artist: "Shinsei Kamattechan",
      musicPath: "/assets/music/music-2.mp3",
    },
    {
      id:6,
      backgroundImage: "/assets/images/poster-3.jpg",
      posterUrl: "/assets/images/poster-3.jpg",
      title: "Fukashigi no Karte",
      album: "Anime",
      year: 2018,
      artist: "Hidehiro Kawai",
      musicPath: "/assets/music/music-3.mp3",
    },
    {
      id:7,
      backgroundImage: "/assets/images/poster-4.jpg",
      posterUrl: "/assets/images/poster-4.jpg",
      title: "Shake & Shake",
      album: "Anime",
      year: 2022,
      artist: "Sumika",
      musicPath: "/assets/music/music-4.mp3",
    },
    {
      id:8,
      backgroundImage: "/assets/images/poster-5.jpg",
      posterUrl: "/assets/images/poster-5.jpg",
      title: "Kick Back",
      album: "Anime",
      year: 2022,
      artist: "Kenshi Yonezu",
      musicPath: "/assets/music/music-5.mp3",
    },
    {
      id:9,
      backgroundImage: "/assets/images/poster-6.jpg",
      posterUrl: "/assets/images/poster-6.jpg",
      title: "Mixed Nuts",
      album: "Anime",
      year: 2022,
      artist: "Hige Dandism",
      musicPath: "/assets/music/music-6.mp3",
    },
    {
      id:10,
      backgroundImage: "/assets/images/poster-7.jpg",
      posterUrl: "/assets/images/poster-7.jpg",
      title: "Idol",
      album: "Anime",
      year: 2023,
      artist: "YOASOBI",
      musicPath: "/assets/music/music-7.mp3",
    },
  ]; */

export const songs = [
  {
    id:1,
    backgroundImage: "assets/images/calm-down.jpg",
    posterUrl: "assets/images/calm-down.png",
    title: "Calm Down",
    album: "Audio",
    year: 2023,
    artist: "Rema ft Gomez",
    musicPath: "https://cdn.tunezjam.com/video/Rema-Ft-Selena-Gomez-Calm-Down-Video-(TunezJam.com).mp4",
  },
  {
    id:2,
    backgroundImage: "assets/images/local-poster-2.jpg",
    posterUrl: "assets/images/lonely-at-the-top.jpg",
    title: "Lonely at the top ",
    album: "Audio",
    year: 2023,
    artist: "Asake",
    musicPath: "https://cdn.trendybeatz.com/audio/Asake-Lonely-At-The-Top-(TrendyBeatz.com).mp3",
  },
  {
    id:3,
    backgroundImage: "assets/images/unavailable.jpg",
    posterUrl: "./assets/images/unavailable.jpg",
    title: "Unavailable",
    album: "Audio",
    year: 2023,
    artist: "Davido ft Musa",
    musicPath: "https://cdn.trendybeatz.com/audio/Davido-Ft-Musa-Keys-Unavailable-New-Song-(TrendyBeatz.com).mp3",
  }
];